#L O G I N
#Can be a domain, too
ipAddress: "changeme"
virtualServerId: 1
#Username for bot
username: "serveradmin"
#Password for bot
password: "passwordhere"

#C O N F I G U R E  F E E D S
#The interval to update the feeds in minutes
autoUpdate: 15